name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and push Docker image
      run: 
        docker login -u "kiran11113" --password "@Zxcvbnm1"
        docker image build-t kiran11113/flaskapp:v1 .
        docker push kiran11113/flaskapp:v1
